services:
  - type: web
    name: qgig-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: DATABASE_URL
        fromDatabase:
          name: qgig-db
          property: connectionString

databases:
  - name: qgig-db
    plan: free
    databaseName: qgig
    user: qgig
